float64[] goal_twist
float64[] target_wrench
float64[] wrench_toll
float64[] wrench_deadband
string    target_wrench_frame
string    goal_twist_frame
---
int32  error_code
string error_string
---
float64[] jointValues
