float64    linear_speed
float64    angular_speed
float64    linear_tollerance
float64    angular_tollerance
float64[7] goal                   # absolute position of the goal_frame expressed in the goal_reference_frame
string     goal_link
string     goal_reference_frame
bool       relative_movement
---
int32  error_code
string error_string
---
float64[] jointValues

